language: java
jdk:
  - oraclejdk8

services:
  - docker

script: mvn verify -Ptest

after_success:
  - docker build -t paukiatwee/budgetapp .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push paukiatwee/budgetapp
